services:
  zookeeper:
    image: zookeeper:3.9.2
    container_name: zookeeper
    restart: always
    volumes:
      - zk-logs:/logs
      - zk-data:/data
      - zk-datalog:/datalog

  nimbus:
    image: storm:2.7.0
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - storm-nimbus-logs:/logs

  supervisor:
    image: storm:2.7.0
    container_name: supervisor
    command: storm supervisor -c worker.childopts=-Xmx%HEAP-MEM%m
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - storm-supervisor-logs:/logs

  ui:
    image: storm:2.7.0
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - storm-ui-logs:/logs

  runner:
    image: digitalpebble/storm_maven:2.7.0
    container_name: runner
    depends_on:
      - nimbus
    volumes:
      - "./crawldata:/crawldata"

# the logviewer does not work in a container environment 
# see https://issues.apache.org/jira/browse/STORM-1759

#  logviewer:
#    image: storm:2.4.0-temurin
#    container_name: logviewer
#    command: storm logviewer
#    depends_on:
#      - nimbus
#      - supervisor
#    restart: always
#    ports:
#      - "127.0.0.1:8000:8000"

  frontier:
    image: crawlercommons/url-frontier
    container_name: frontier
    command: rocksdb.path=/crawldir/rocksdb
    ports:
      - "127.0.0.1:7071:7071"
    volumes:
      - ./frontier:/crawldir

volumes:
  opensearch-data1:
  opensearch-data2:
  storm-ui-logs:
  storm-nimbus-logs:
  storm-supervisor-logs:
  zk-logs:
  zk-data:
  zk-datalog:
