version: '3.1'

services:
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: always

  frontier:
    image: crawlercommons/url-frontier
    container_name: frontier
    command: rocksdb.path=/crawldir/rocksdb
    ports:
      - "127.0.0.1:7071:7071"
    volumes:
      - /data/stormcrawler-docker:/crawldir

#  prometheus:
#    image: prom/prometheus 
#    container_name: prometheus
#    ports:
#      - "127.0.0.1:9090:9090"

#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    ports:
#      - "127.0.0.1:3000:3000"

#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
#    container_name: elastic
#    environment:
#      - node.name=elastic
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - TAKE_FILE_OWNERSHIP=true
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - "127.0.0.1:9200:9200"
#    volumes:
#      - es-data:/usr/share/elasticsearch/data
#
#  kibana:
#    image: kibana:7.17.2
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_URL: http://elastic:9200
#      ELASTICSEARCH_HOSTS: http://elastic:9200
#    depends_on:
#      - elastic
#    ports:
#      - "127.0.0.1:5601:5601"

  builder:
    image: digitalpebble/storm_maven:2.4.0
    container_name: builder
    depends_on:
      - nimbus
    volumes:
      - "./crawldata:/crawldata"

  nimbus:
    image: storm:2.4.0
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    volumes:
      - storm-nimbus-logs:/logs

  supervisor:
    image: storm:2.4.0
    container_name: supervisor
    command: storm supervisor -c worker.childopts=-Xmx%HEAP-MEM%m
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - storm-supervisor-logs:/logs

  ui:
    image: storm:2.4.0
    container_name: ui
    command: storm ui
    depends_on:
      - nimbus
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - storm-ui-logs:/logs

# the logviewer does not work in a container environment 
# see https://issues.apache.org/jira/browse/STORM-1759

#  logviewer:
#    image: storm:2.4.0
#    container_name: logviewer
#    command: storm logviewer
#    depends_on:
#      - nimbus
#      - supervisor
#    restart: always
#    ports:
#      - "127.0.0.1:8000:8000"

volumes:
  frontier-data:
    driver: local
  es-data:
    driver: local
  storm-ui-logs:
    driver: local
  storm-nimbus-logs:
    driver: local
  storm-supervisor-logs:
    driver: local
